var Router = Ember.Router.extend();

Router.map(function() {
  this.resource('todos', { path: '/' }, function() {
    // this.route('index', { path: '/' });  // this route is autogenerated
    this.route('active');
    this.route('completed');
  });
});

// use pushState instead of hashchange on URLs
Router.reopen({
  location: 'history'
});

export default Router;